### ISSUE TITLE
Validate algorithm image produces a valid TSV

### ISSUE THREAD

**Issue by danjjl** [esl-epfl/szcore#25]
We are missing a CI job that checks the algorithm docker image and produces a valid TSV output.

This job should check:

- [x] File is produced at the correct location with the correct filename (i.e. it should check the value of the environment variable `$OUTPUT` is respected)
- [x] Check the TSV output complies with the SzCORE definition

This is part of CI action [PR-check](https://github.com/esl-epfl/szcore/blob/main/.github/workflows/pr-check.yml)

**Comment by cmdoret** [comment]
Do we have a small, non-sensitive dummy edf file we could use for this technical check? It could be directly embedded in the repo. To keep the PR check simple and fast, it could then run on this file directly without connecting to s3

**Comment by danjjl** [comment]
These files, in this repo were specifically designed for this purpose:

https://github.com/esl-epfl/epilepsy2bids/tree/main/tests

We could re-use them

**Comment by cmdoret** [comment]
Thankks @danjjl, I tried running the gotman_1982 image on the file PN00-5_sample.edf from above repo, however I get: 

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/gotman_1982/__main__.py", line 12, in <module>
    main(args.input, args.output)
  File "/usr/local/lib/python3.12/site-packages/gotman_1982/main.py", line 9, in main
    eeg = Eeg.loadEdfAutoDetectMontage(edfFile=edf_file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/epilepsy2bids/eeg.py", line 221, in loadEdfAutoDetectMontage
    raise ValueError(
ValueError: Unrecognized electrode: EEG Fp1. Expected Fp1 or Fp1-Avg or Fp1-F3
```

Is that a bug, or am I using the wrong file?

**Comment by cmdoret** [comment]
Nevermind, it seems to work with P_ID10_r5_sample.edf

**Comment by danjjl** [comment]
Sorry, I didn't provide enough context.

These files are raw files from datasets that are not yet BIDS-SZCORE compatible.

Here are two files that are converted and that can directly be used for testing.
[testFiles.zip](https://github.com/user-attachments/files/18062428/testFiles.zip)
