### ISSUE TITLE
Improve s3 link parsing to make it more intuitive and dynamic in Evaluator

### ISSUE THREAD

**Issue by EishaMazhar** [esl-epfl/szcore#37]
Currently parsing the s3 links is not so intuitive and might break anytime. Therefore, Improve s3 link parsing to make it more intuitive and dynamic in the Evaluator

**Comment by danjjl** [comment]
Can you provide more details on this?
I might have already solved it with the refactoring of the evaluation code

**Comment by danjjl** [comment]
Closing as I am not sure this is still relevant 
(Do reopen if it is needed)
